item/urls.py
from django.urls import path
from . import views

app_name = 'item'
urlpatterns = [
    path('', views.index, name='index'),
    path('details/<int:id>/', views.details, name='details'),
    path('newItem/', views.newItem, name='newItem'),
    path('newItem/<int:id>/', views.newItem, name='newItem'),
    path('editItem/<int:id>/', views.editItem, name='editItem'),
    path('completeItem/<int:id>/', views.completeItem, name='completeItem'),
    path('deleteItem/<int:id>/', views.deleteItem, name='deleteItem')
]

todoList/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('item.urls')),
    path('item/', include('item.urls')),
    path('users/', include('users.urls'))
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'users'
urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('logout/', views.logoutView, name="logout"),
    path('register/', views.register, name='register')
]

item/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User


class Item(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    deadline = models.DateTimeField(blank=False)
    PRIORITIES = [
        ('L', 'Low'),
        ('M', 'Medium'),
        ('H', 'High'),
    ]
    priority = models.CharField(max_length=1, choices=PRIORITIES, default='L')
    createdAt = models.DateTimeField(default=datetime.now, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    isComplete = models.BooleanField(default=0)

    class Meta:
        verbose_name_plural = 'items'

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

item/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['title', 'body', 'deadline', 'priority']
        lables = {'body': ''}
        widgets = {'event_date': forms.DateInput(
            attrs={'class': 'datepicker'})}

item/views.py
from django.shortcuts import render
from .models import Item
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .forms import ItemForm


@login_required
def index(request):
    items = Item.objects.filter(owner=request.user).order_by('deadline')
    context = {
        'title': "Todo List",
        'items': items
    }
    return render(request, 'item/index.html', context)


@login_required
def details(request, id):
    item = Item.objects.get(id=id)
    if item.owner != request.user:
        raise Http404
    context = {
        'item': item
    }
    return render(request, 'item/details.html', context)


@login_required
def newItem(request):
    if request.method != 'POST':
        form = ItemForm
    else:
        form = ItemForm(data=request.POST)
        if form.is_valid():
            newItem = form.save(commit=False)
            newItem.owner = request.user
            newItem.save()
            return HttpResponseRedirect(reverse('item:index'))

    context = {'form': form}
    return render(request, 'item/newItem.html', context)


@login_required
def completeItem(request, id):
    item = Item.objects.get(id=id)
    item.isComplete = True
    item.save()
    return HttpResponseRedirect(reverse('item:index'))


@login_required
def deleteItem(request, id):
    Item.objects.get(id=id).delete()
    return HttpResponseRedirect(reverse('item:index'))


@login_required
def editItem(request, id):
    item = Item.objects.get(id=id)

    if request.method != 'POST':
        form = ItemForm(instance=item)
    else:
        form = ItemForm(instance=item, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('item:index'))

    context = {'item': item, 'form': form}
    return render(request, 'item/editItem.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import logout


def logoutView(request):
    logout(request)
    return HttpResponseRedirect(reverse('item:index'))


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,
                    password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('item:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)

item/templates/item/base.html
{%load bootstrap3%}
<!DOCTYPE html>
<html lang="en">
<head>
		<meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Todo List</title>
    {%bootstrap_css%}
    {%bootstrap_javascript%}

	<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
	<link rel="stylesheet" href="/resources/demos/style.css">
	<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
	<script>
		$( function() {
		$( "#id_deadline" ).datepicker();
		} );
	</script>

</head>

<body>
   <title>
       <h1>Todo List</h1>
    </title>
    <nav class="navbar navbar-default navbar-static-top">
	<div class="container">
	    <div class="navbar-header">
		<button class="navbar-toggle collapsed"
		    data-toggle="callapse" data-target="#navbar"
		    aria-expanded="false" aria-controls="navbar">
		</button>
		<a class="navbar-brand" href="{%url 'item:index'%}">
		    Todo List
		</a>
	    </div>

	    <div id="navbar" class="navbar-collapse collapse">
		<ul class="nav navbar-nav navbar-right">
		    {%if user.is_authenticated%} 
			<li><a>Hello, {{user.username}}</a></li>
			<li><a href="{%url 'users:logout'%}">log out</a></li>
		    {%else%}
			<li><a href="{%url 'users:register'%}">register</a></li>
			<li><a href="{%url 'users:login'%}">log in</a></li>
		    {%endif%}
		</ul>
	    </div>
	</div>
    </nav>
    <div class="container">
        <div class="page-header">
	    {%block header%}  
	    {%endblock header%}  
	</div>
        <div>
	    {%block content%}  
	    {%endblock content%}  
	</div>
    </div>
</body>
</html>

item/templates/item/details.html
{%extends 'item/base.html'%}

{%block header%}
	<h1>{{item.title}}</h1>
{%endblock header%}

{%block content%}
	<div class="panel panel-default">
		<div class="panerl-heading">
			<h3> Deadline: {{item.deadline|date:'d M, Y H:i'}} </h3>
		</div>
		<div class="panel-body">
			{{item.body|linebreaks}}
			Created at: {{item.createdAt}}
			<br>
			{% now "Y-m-d" as todayDate %}
			{%if todayDate > item.deadline|date:"Y-m-d" and item.isComplete == False %}
				<a class="btn btn-danger" href="#">Deadline Passed!</a>
			{%else%}
				<a class="btn btn-success"
				href="{%url 'item:completeItem' item.id%}">Complete Item
				</a>
			{%endif%}
			<br/>
			<a href="{%url 'item:editItem' item.id%}">edit item
			</a>
			| 
			<a onclick="return confirm('Are you sure?')" 
				href="{%url 'item:deleteItem' item.id%}">delete item
			</a>
		</div>
	</div>
{%endblock%}

item/templates/item/editItem.html
{%extends "item/base.html"%}
{%block content%}
    <p>Edit item: </p>
    <form action="{%url 'item:editItem' item.id%}" method='post'>
	{%csrf_token%}
	{{form.as_p}}
	<button name='submit'>save changes</button>
    </form>
{%endblock content%}

item/templates/item/index.html
{%extends 'item/base.html'%}

{%block header%}
<div class="jumbotron">
    <h3>{{user.username}}'s Todo list</h3>
</div>
{%endblock header%}

{%block content%}
    <a href="{%url 'item:newItem'%}">Add new item</a>
    <ul>
	{%for item in items%}
	<div role="alert" 
	{% now "Y-m-d" as todayDate %}
	    {%if todayDate > item.deadline|date:"Y-m-d" and item.isComplete == False %}
		class="alert alert-danger"
	    {%elif item.isComplete == True%}
		class="align-top alert alert-success"
	    {%else%}
		class="alert alert-info"
	    {%endif%} >

	    <a href="/item/details/{{item.id}}" 
		class="alert-link">{{item.title}}</a>
		Deadline: 
		{{item.deadline|date:'d M, Y H:i'}}
	    {%if todayDate > item.deadline|date:"Y-m-d" and item.isComplete == False%}
		<div style="font-size:2rem" class="pull-right ">
		    &#x274c;Deadline passed
		</div>
	    {%elif item.isComplete == False%}
		<div class="pull-right ">{{item.priority}} priority</div>
	    {%endif%}

	    {%if item.isComplete == True%}
		<div style="font-size:2rem" class="pull-right ">
		    &#x2713;Complete 
		</div>
	    {%endif%}
	    </div>

	{%empty%}
	    <li>No items have been added yet</li>
	{%endfor%}
</ul>
{%endblock%}

item/templates/item/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Todo List</title>
</head>
<body>
   <header>
       <h1>Todo List</h1>
   </header>
   <div class="container">
       {%block content%}
       {%endblock%}
   </div>
   <br>
   <a href="/admin">Admin Login</a>
</body>
</html>

item/templates/item/newItem.html
{%extends "item/base.html"%}
{%load bootstrap3%}

{%block header%}
	<h2>Add a new item:</h2>
</script>
{%endblock header%}

{%block content%}
	<form action="{%url 'item:newItem'%}" method='post' class="form">
		{%csrf_token%}
		{%bootstrap_form form%}
		<button name="submit" class="btn btn-primary">add item</button>
	</form>
{%endblock content%}

users/templates/users/login.html
{%extends 'item/base.html'%}
{%block content%}
    {%if form.erros%}
	<p>Your username and password didn't match. Please try again.</p>
    {%endif%}
    <form action="{%url 'users:login'%}" method="post">
	{%csrf_token%}
	{{form.as_p}}
	<button name='submit'>log in</button>
	<input type="hidden" name='next' value="{%url 'item:index'%}"/>
    </form>
{%endblock content%}

users/templates/users/logout.html
{%extends 'item/base.html'%}
{%load bootstrap3%}

{%block header%}
    <h2>Log into your account</h2>
{%endblock header%}

{%block content%}
    {%if form.erros%}
	<p>Your username and password didn't match. Please try again.</p>
    {%endif%}
    <form class="form" action="{%url 'users:login'%}" method="post">
	{%csrf_token%}
	{%bootstrap_form form%}
	{%buttons%}
	    <button name="submit" class="btn btn-primary">log in</button>
	{%endbuttons%}
	<input type="hidden" name='next' value="{%url 'item:index'%}"/>
    </form>
{%endblock content%}

users/templates/users/register.html
{%extends 'item/base.html'%}
{%block content%}
    <form action="{%url 'users:register'%}" method="post">
	{%csrf_token%}
	{{form.as_p}}
	<button name='submit'>register</button>
	<input type="hidden" name='next' value="{%url 'item:index'%}"/>
    </form>
{%endblock content%}